Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - 'lib/device/**/*'
Metrics/AbcSize:
  Exclude:
    - 'lib/device/**/*'
