require_relative 'device/publishables/entitiable'
require_relative 'device/publishables/topicable'
require_relative 'device/publishables/helper'
require_relative 'device/publishable'

require_relative 'device/gen_1/versionable'
require_relative 'device/gen_1/single_input'
require_relative 'device/gen_1/double_input'
require_relative 'device/gen_1/single_switch_output'

require_relative 'device/gen_2/versionable'
require_relative 'device/gen_2/energy_sensor'
require_relative 'device/gen_2/power_sensor'
require_relative 'device/gen_2/temperature_sensor'
require_relative 'device/gen_2/voltage_sensor'
require_relative 'device/gen_2/current_sensor'
require_relative 'device/gen_2/output_sensor'
require_relative 'device/gen_2/input_sensor'
require_relative 'device/gen_2/iterative_sensor'

require_relative 'device/shelly_1'
require_relative 'device/shelly_1_pm'
require_relative 'device/shelly_2_5'
require_relative 'device/shelly_dimmer_2'
require_relative 'device/shelly_plus_1_pm'
require_relative 'device/shelly_plus_2_pm'
require_relative 'device/shelly_em'

require_relative 'device/mapper'
