require_relative 'device/publishable'
require_relative 'device/shelly_1'
require_relative 'device/shelly_1_pm'
require_relative 'device/shelly_2_5'
require_relative 'device/shelly_dimmer_2'
require_relative 'device/shelly_plus_1_pm'
require_relative 'device/shelly_plus_2_pm'
require_relative 'device/shelly_em'
