require_relative 'entities/anemic_entity'
require_relative 'entities/binary_sensor'
require_relative 'entities/sensor'
require_relative 'entities/switch'
require_relative 'entities/number'
require_relative 'entities/light'
require_relative 'entities/update'
