name: Docker Buildx for GHCR on Release

on:
  pull_request:
    types: [closed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      contents: write
      packages: write
      actions: read

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3
        if: ${{ github.event.pull_request.merged == true }}

      - name: Extract Tag from Commit Message
        id: extract_tag
        run: |
          LAST_COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
          
          if [[ $LAST_COMMIT_MESSAGE =~ tag:([^[:space:]]+)[[:space:]]+(.*) ]]; then
            echo "Custom tag found: ${BASH_REMATCH[1]}"
            echo "Custom message: ${BASH_REMATCH[2]}"
            echo "custom_tag=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "custom_message=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
            echo "should_continue=true" >> $GITHUB_OUTPUT
          else
            echo "Unable to extract tag and message"
            echo "Message=${LAST_COMMIT_MESSAGE}"
            echo "should_continue=false" >> $GITHUB_OUTPUT
          fi
        if: ${{ github.event.pull_request.merged == true }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ steps.extract_tag.outputs.should_continue == 'true' }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.extract_tag.outputs.should_continue == 'true' }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha-shelly-bridge:${{ steps.extract_tag.outputs.custom_tag }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ha-shelly-bridge:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ha-shelly-bridge:cache,mode=max
        if: ${{ steps.extract_tag.outputs.should_continue == 'true' }}
