name: Notify Slack of CI Results

on:
  check_run:
    types: [completed]
jobs:
  slack-notification-ci-results:
    runs-on: ubuntu-latest
    if: startsWith(github.event.check_run.name, 'ci/circleci') || github.event.check_run.app.slug == 'circleci'

    steps:
      - name: Debug status payload
        run: echo '${{ toJson(github.event) }}'
      - name: Check if commit has an open PR
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
        run: |
          PRS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=repo:${{ github.repository }}+sha:$SHA+is:pr+is:open")

          TOTAL=$(echo "$PRS" | jq '.total_count')
          if [ "$TOTAL" -gt 0 ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            PR_NUMBER=$(echo "$PRS" | jq -r '.items[0].number')
            echo "pr_number="$PR_NUMBER"
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Check for Artifact
        id: check-artifact
        if: steps.check_pr.outputs.pr_exists == 'true'
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
                        jq -r '.artifacts | map(select(.name == "slack-thread-ts-${{ steps.check_pr.outputs.pr_number }}")) | sort_by(.created_at)  | .[-1].id')
          if [[ -n "$ARTIFACT_ID" ]]; then
            echo "artifact_exists=true" >> $GITHUB_OUTPUT
            echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          else
            echo "artifact_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GHCR_ACCESS_KEY }}
      - name: Download Artifact
        id: download-artifact
        if: steps.check_pr.outputs.pr_exists == 'true'
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.check-artifact.outputs.artifact_id }}/zip" \
            -o artifact.zip
          unzip artifact.zip -d artifact_contents
          THREAD_TS=$(cat artifact_contents/slack_thread_ts_${{ steps.check_pr.outputs.pr_number }}.txt)
          echo "thread_ts=$THREAD_TS" >> $GITHUB_OUTPUT
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' }}
      - name: Add Status Check Failure
        id: pr-comment-add
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event.state == 'failure' && steps.check_pr.outputs.pr_exists == 'true' }}
        with:
          errors: false
          method: reactions.add
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: ${{ steps.download-artifact.outputs.thread_ts }}
            name: "rotating-light-red"
      - name: Remove Status Check Failure
        id: pr-comment-remove
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event.state == 'success' && steps.check_pr.outputs.pr_exists == 'true' }}
        with:
          errors: false
          method: reactions.remove
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: ${{ steps.download-artifact.outputs.thread_ts }}
            name: "rotating-light-red"
