name: Notify Slack of CI Failure

on:
  check_suite:
    types: [completed]
jobs:
  slack-notification-ci-failure:
    runs-on: ubuntu-latest
    if: >
      github.event.check_suite.pull_requests[0] != null &&
      (github.event.check_suite.conclusion == 'success' || github.event.check_suite.conclusion == 'failrue')
    steps:
      - name: Check for Artifact
        id: check-artifact
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
                        jq -r '.artifacts | map(select(.name == "slack-thread-ts-${{ github.event.pull_request.number }}")) | sort_by(.created_at)  | .[-1].id')
          if [[ -n "$ARTIFACT_ID" ]]; then
            echo "artifact_exists=true" >> $GITHUB_OUTPUT
            echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          else
            echo "artifact_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GHCR_ACCESS_KEY }}
      - name: Download Artifact
        id: download-artifact
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.check-artifact.outputs.artifact_id }}/zip" \
            -o artifact.zip
          unzip artifact.zip -d artifact_contents
          THREAD_TS=$(cat artifact_contents/slack_thread_ts_${{github.event.pull_request.number}}.txt)
          echo "thread_ts=$THREAD_TS" >> $GITHUB_OUTPUT
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' }}
      - name: Add Status Check Failure
        id: pr-comment-add
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event.check_suite.conclusion == 'failure' }}
        with:
          errors: false
          method: reactions.add
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: ${{ steps.download-artifact.outputs.thread_ts }}
            name: "rotating-light-red"
      - name: Remove Status Check Failure
        id: pr-comment-remove
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event.check_suite.conclusion == 'success' }}
        with:
          errors: false
          method: reactions.remove
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: ${{ steps.download-artifact.outputs.thread_ts }}
            name: "rotating-light-red"
