name: Notify Slack of PR Closure

on:
  pull_request:
    types: [closed]

jobs:
  slack-notification-close:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == false }}
    steps:
      - name: Check for Artifact
        id: check-artifact
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
                        jq -r '.artifacts | map(select(.name == "slack-thread-ts-${{ github.event.pull_request.number }}")) | sort_by(.created_at)  | .[-1].id')
          if [[ -n "$ARTIFACT_ID" ]]; then
            echo "artifact_exists=true" >> $GITHUB_OUTPUT
            echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          else
            echo "artifact_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GHCR_ACCESS_KEY }}
      - name: Download Artifact
        id: download-artifact
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}/zip" \
            -o artifact.zip
          unzip artifact.zip -d artifact_contents
          THREAD_TS=$(cat artifact_contents/slack_thread_ts_${{github.event.pull_request.number}}.txt)
          echo "thread_ts=$THREAD_TS" >> $GITHUB_OUTPUT
          echo "Applying Thread TS TO $THREAD_TS"
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
      - name: Add PR Closed Emoji
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
        with:
          errors: true
          method: reactions.add
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: ${{ steps.download-artfiact.outputs.thread_ts }}
            name: "pr-closed"
      - name: Add who closed the PR
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ steps.check-artifact.outputs.artifact_exists == 'true' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: ${{ steps.download-artfiact.outputs.thread_ts }}
            text: "PR Closed by ${{ github.actor }}"
