name: PR Slack Notifications

on:
  pull_request:
    types: [opened, closed, reopened]
  check_suite:
    types: [completed]
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        id: slack-message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: ${{ github.event.pull_request.user.login }} created PR <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}>
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' ||  github.event.action == 'reopened')

      - name: Debug Message TS
        run: |
          echo "Message TS: ${{ steps.slack-message.outputs.ts  }}"
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
